language: android
dist: trusty

env:
  global:
    - ANDROID_API_LEVEL=30
    - ANDROID_BUILD_TOOLS_VERSION=30.0.3

android:
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
  components:
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION

    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - echo no | android create avd --force -n test -t android-27 --abi google_apis/armeabi-v7a
    - emulator -avd test -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &
before_script:
  - mkdir -p "$ANDROID_HOME/licenses"
  - cp ./google-licenses/* "$ANDROID_HOME/licenses/"
script:
  - ./gradlew build check